/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.0.2-a-1-g742c4f3-dirty

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0x00000000,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1008_manufacturerDeviceName = {'M', 'E', 'T', 'R', 'A', '-', 'L', 0},
    .x1009_manufacturerHardwareVersion = {'1', '2', '3', '4', '5', 0},
    .x100A_manufacturerSoftwareVersion = {'0', '.', '0', '.', '0', 0},
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x03E8,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    },
    .x1800_TPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByTPDO = 0x00000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x03E8,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1801_TPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByTPDO = 0x00000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1802_TPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByTPDO = 0x00000380,
        .transmissionType = 0xFE,
        .inhibitTime = 0x03E8,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1803_TPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByTPDO = 0x00000480,
        .transmissionType = 0xFE,
        .inhibitTime = 0x03E8,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1804_TPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByTPDO = 0x000001B1,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1805_TPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByTPDO = 0x000002B1,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1806_TPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByTPDO = 0x000003B1,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1807_TPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByTPDO = 0x000004B1,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedObjects = 0x04,
        .mappedObject_1 = 0x64010010,
        .mappedObject_2 = 0x64020010,
        .mappedObject_3 = 0x64030010,
        .mappedObject_4 = 0x64090010
    },
    .x1A01_TPDOMappingParameter = {
        .numberOfMappedObjects = 0x05,
        .mappedObject_1 = 0x674C0010,
        .mappedObject_2 = 0x64040010,
        .mappedObject_3 = 0x64050010,
        .mappedObject_4 = 0x640A0008,
        .mappedObject_5 = 0x640B0008
    },
    .x1A02_TPDOMappingParameter = {
        .numberOfMappedObjects = 0x05,
        .mappedObject_1 = 0x64060010,
        .mappedObject_2 = 0x64070010,
        .mappedObject_3 = 0x64080010,
        .mappedObject_4 = 0x10010008,
        .mappedObject_5 = 0x640E0008
    },
    .x1A03_TPDOMappingParameter = {
        .numberOfMappedObjects = 0x04,
        .mappedObject_1 = 0x67310010,
        .mappedObject_2 = 0x67320010,
        .mappedObject_3 = 0x67350008,
        .mappedObject_4 = 0x67110008
    },
    .x1A04_TPDOMappingParameter = {
        .numberOfMappedObjects = 0x02,
        .mappedObject_1 = 0x67330010,
        .mappedObject_2 = 0x67340010
    },
    .x1A05_TPDOMappingParameter = {
        .numberOfMappedObjects = 0x04,
        .mappedObject_1 = 0x67410010,
        .mappedObject_2 = 0x67420010,
        .mappedObject_3 = 0x67430010,
        .mappedObject_4 = 0x67440010
    },
    .x1A06_TPDOMappingParameter = {
        .numberOfMappedObjects = 0x04,
        .mappedObject_1 = 0x67450010,
        .mappedObject_2 = 0x67460010,
        .mappedObject_3 = 0x67470010,
        .mappedObject_4 = 0x67480010
    },
    .x1A07_TPDOMappingParameter = {
        .numberOfMappedObjects = 0x03,
        .mappedObject_1 = 0x67490010,
        .mappedObject_2 = 0x674A0010,
        .mappedObject_3 = 0x674B0010
    }
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x6401_aterialPressure = 0x0000,
    .x6402_arterialFlowRate = 0x0000,
    .x6403_arterialSensorFlags = 0x0000,
    .x6404_portalVeinFlowRate = 0x0000,
    .x6405_portalVeinSensorFlags = 0x0000,
    .x6406_IVC_Pressure = 0x0000,
    .x6407_IVC_FlowRate = 0x0000,
    .x6408_IVC_SensorFlags = 0x0000,
    .x6409_bileFlowRate = 0x0000,
    .x640A_bileTemperature = 0x00,
    .x640B_ambientTemperature_1 = 0x00,
    .x640C_ambientTemperature_2 = 0x00,
    .x640D_ambientTemperature_3 = 0x00,
    .x640E_levelSwitchState = 0x00,
    .x6701_startCalibration = 0x00,
    .x6702_personality = 0x0000,
    .x6703_K_code = {'?', '?', '?', '?', 0, 0},
    .x6704_startMeasurements = 0x00,
    .x6711_terumoPresent = 0x00,
    .x6712_serialNumber = {'N', 'O', 'T', ' ', 'S', 'E', 'T', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x6713_K_CodeDisplay = {'?', '?', '?', '?', 0, 0},
    .x6714_calibrationTimestamp = 0x00000000,
    .x6715_CDI_SoftwareVersion = {'N', 'O', 'T', ' ', 'S', 'E', 'T', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x6716_shuntUsed = 0x00,
    .x6721_calibratorPresent = 0x00,
    .x6722_calibratorSerialNumber = {'0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    .x6723_calibratorStateFlags = 0x0000,
    .x6731_terumoCalibratorStatus = 0x0000,
    .x6732_terumoCalibratorStatusFlags = 0x0000,
    .x6733_terumoCalibratorGas_1 = 0x0000,
    .x6734_terumoCalibratorGas_2 = 0x0000,
    .x6735_terumoCalibratorPresenceFlags = 0x00,
    .x6741_terumoArterialpHpHStat = 0,
    .x6742_terumoArterialpHAStat = 0,
    .x6743_terumoArterialCO2pHStat = 0,
    .x6744_terumoArterialCO2AStat = 0,
    .x6745_terumoArterialO2pHStat = 0,
    .x6746_terumoArterialO2AStat = 0,
    .x6747_terumoArterialCalculatedSO2pHStat = 0,
    .x6748_terumoArterialCalculatedSO2AStat = 0,
    .x6749_terumoArterialHCO3 = 0,
    .x674A_terumoArterialPotassium = 0,
    .x674B_terumoArterialTemperature = 0,
    .x674C_portalVeinPressure = 0x0000
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1802_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1803_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1804_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1805_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1806_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1807_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1A00_TPDOMappingParameter[5];
    OD_obj_record_t o_1A01_TPDOMappingParameter[6];
    OD_obj_record_t o_1A02_TPDOMappingParameter[6];
    OD_obj_record_t o_1A03_TPDOMappingParameter[5];
    OD_obj_record_t o_1A04_TPDOMappingParameter[3];
    OD_obj_record_t o_1A05_TPDOMappingParameter[5];
    OD_obj_record_t o_1A06_TPDOMappingParameter[5];
    OD_obj_record_t o_1A07_TPDOMappingParameter[4];
    OD_obj_var_t o_6401_aterialPressure;
    OD_obj_var_t o_6402_arterialFlowRate;
    OD_obj_var_t o_6403_arterialSensorFlags;
    OD_obj_var_t o_6404_portalVeinFlowRate;
    OD_obj_var_t o_6405_portalVeinSensorFlags;
    OD_obj_var_t o_6406_IVC_Pressure;
    OD_obj_var_t o_6407_IVC_FlowRate;
    OD_obj_var_t o_6408_IVC_SensorFlags;
    OD_obj_var_t o_6409_bileFlowRate;
    OD_obj_var_t o_640A_bileTemperature;
    OD_obj_var_t o_640B_ambientTemperature_1;
    OD_obj_var_t o_640C_ambientTemperature_2;
    OD_obj_var_t o_640D_ambientTemperature_3;
    OD_obj_var_t o_640E_levelSwitchState;
    OD_obj_var_t o_6701_startCalibration;
    OD_obj_var_t o_6702_personality;
    OD_obj_var_t o_6703_K_code;
    OD_obj_var_t o_6704_startMeasurements;
    OD_obj_var_t o_6711_terumoPresent;
    OD_obj_var_t o_6712_serialNumber;
    OD_obj_var_t o_6713_K_CodeDisplay;
    OD_obj_var_t o_6714_calibrationTimestamp;
    OD_obj_var_t o_6715_CDI_SoftwareVersion;
    OD_obj_var_t o_6716_shuntUsed;
    OD_obj_var_t o_6721_calibratorPresent;
    OD_obj_var_t o_6722_calibratorSerialNumber;
    OD_obj_var_t o_6723_calibratorStateFlags;
    OD_obj_var_t o_6731_terumoCalibratorStatus;
    OD_obj_var_t o_6732_terumoCalibratorStatusFlags;
    OD_obj_var_t o_6733_terumoCalibratorGas_1;
    OD_obj_var_t o_6734_terumoCalibratorGas_2;
    OD_obj_var_t o_6735_terumoCalibratorPresenceFlags;
    OD_obj_var_t o_6741_terumoArterialpHpHStat;
    OD_obj_var_t o_6742_terumoArterialpHAStat;
    OD_obj_var_t o_6743_terumoArterialCO2pHStat;
    OD_obj_var_t o_6744_terumoArterialCO2AStat;
    OD_obj_var_t o_6745_terumoArterialO2pHStat;
    OD_obj_var_t o_6746_terumoArterialO2AStat;
    OD_obj_var_t o_6747_terumoArterialCalculatedSO2pHStat;
    OD_obj_var_t o_6748_terumoArterialCalculatedSO2AStat;
    OD_obj_var_t o_6749_terumoArterialHCO3;
    OD_obj_var_t o_674A_terumoArterialPotassium;
    OD_obj_var_t o_674B_terumoArterialTemperature;
    OD_obj_var_t o_674C_portalVeinPressure;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &OD_PERSIST_COMM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 7
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = &OD_PERSIST_COMM.x1009_manufacturerHardwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 5
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &OD_PERSIST_COMM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 5
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1804_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1804_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1805_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1805_TPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1805_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1805_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1805_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1805_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1805_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1805_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1806_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1806_TPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1806_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1806_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1806_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1806_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1806_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1806_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1807_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1807_TPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1807_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1807_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1807_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1807_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1807_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1807_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.mappedObject_3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.mappedObject_4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.mappedObject_3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.mappedObject_4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.mappedObject_5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.mappedObject_3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.mappedObject_4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.mappedObject_5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.mappedObject_3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.mappedObject_4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A04_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A04_TPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A05_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A05_TPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A05_TPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A05_TPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A05_TPDOMappingParameter.mappedObject_3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A05_TPDOMappingParameter.mappedObject_4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A06_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A06_TPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A06_TPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A06_TPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A06_TPDOMappingParameter.mappedObject_3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A06_TPDOMappingParameter.mappedObject_4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A07_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A07_TPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A07_TPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A07_TPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A07_TPDOMappingParameter.mappedObject_3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_6401_aterialPressure = {
        .dataOrig = &OD_RAM.x6401_aterialPressure,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6402_arterialFlowRate = {
        .dataOrig = &OD_RAM.x6402_arterialFlowRate,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6403_arterialSensorFlags = {
        .dataOrig = &OD_RAM.x6403_arterialSensorFlags,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6404_portalVeinFlowRate = {
        .dataOrig = &OD_RAM.x6404_portalVeinFlowRate,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6405_portalVeinSensorFlags = {
        .dataOrig = &OD_RAM.x6405_portalVeinSensorFlags,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6406_IVC_Pressure = {
        .dataOrig = &OD_RAM.x6406_IVC_Pressure,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6407_IVC_FlowRate = {
        .dataOrig = &OD_RAM.x6407_IVC_FlowRate,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6408_IVC_SensorFlags = {
        .dataOrig = &OD_RAM.x6408_IVC_SensorFlags,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6409_bileFlowRate = {
        .dataOrig = &OD_RAM.x6409_bileFlowRate,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_640A_bileTemperature = {
        .dataOrig = &OD_RAM.x640A_bileTemperature,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_640B_ambientTemperature_1 = {
        .dataOrig = &OD_RAM.x640B_ambientTemperature_1,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_640C_ambientTemperature_2 = {
        .dataOrig = &OD_RAM.x640C_ambientTemperature_2,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_640D_ambientTemperature_3 = {
        .dataOrig = &OD_RAM.x640D_ambientTemperature_3,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_640E_levelSwitchState = {
        .dataOrig = &OD_RAM.x640E_levelSwitchState,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6701_startCalibration = {
        .dataOrig = &OD_RAM.x6701_startCalibration,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6702_personality = {
        .dataOrig = &OD_RAM.x6702_personality,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6703_K_code = {
        .dataOrig = &OD_RAM.x6703_K_code[0],
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataLength = 5
    },
    .o_6704_startMeasurements = {
        .dataOrig = &OD_RAM.x6704_startMeasurements,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6711_terumoPresent = {
        .dataOrig = &OD_RAM.x6711_terumoPresent,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6712_serialNumber = {
        .dataOrig = &OD_RAM.x6712_serialNumber[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 16
    },
    .o_6713_K_CodeDisplay = {
        .dataOrig = &OD_RAM.x6713_K_CodeDisplay[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 5
    },
    .o_6714_calibrationTimestamp = {
        .dataOrig = &OD_RAM.x6714_calibrationTimestamp,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_6715_CDI_SoftwareVersion = {
        .dataOrig = &OD_RAM.x6715_CDI_SoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 16
    },
    .o_6716_shuntUsed = {
        .dataOrig = &OD_RAM.x6716_shuntUsed,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_6721_calibratorPresent = {
        .dataOrig = &OD_RAM.x6721_calibratorPresent,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_6722_calibratorSerialNumber = {
        .dataOrig = &OD_RAM.x6722_calibratorSerialNumber[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 16
    },
    .o_6723_calibratorStateFlags = {
        .dataOrig = &OD_RAM.x6723_calibratorStateFlags,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6731_terumoCalibratorStatus = {
        .dataOrig = &OD_RAM.x6731_terumoCalibratorStatus,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6732_terumoCalibratorStatusFlags = {
        .dataOrig = &OD_RAM.x6732_terumoCalibratorStatusFlags,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6733_terumoCalibratorGas_1 = {
        .dataOrig = &OD_RAM.x6733_terumoCalibratorGas_1,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6734_terumoCalibratorGas_2 = {
        .dataOrig = &OD_RAM.x6734_terumoCalibratorGas_2,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6735_terumoCalibratorPresenceFlags = {
        .dataOrig = &OD_RAM.x6735_terumoCalibratorPresenceFlags,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_6741_terumoArterialpHpHStat = {
        .dataOrig = &OD_RAM.x6741_terumoArterialpHpHStat,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6742_terumoArterialpHAStat = {
        .dataOrig = &OD_RAM.x6742_terumoArterialpHAStat,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6743_terumoArterialCO2pHStat = {
        .dataOrig = &OD_RAM.x6743_terumoArterialCO2pHStat,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6744_terumoArterialCO2AStat = {
        .dataOrig = &OD_RAM.x6744_terumoArterialCO2AStat,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6745_terumoArterialO2pHStat = {
        .dataOrig = &OD_RAM.x6745_terumoArterialO2pHStat,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6746_terumoArterialO2AStat = {
        .dataOrig = &OD_RAM.x6746_terumoArterialO2AStat,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6747_terumoArterialCalculatedSO2pHStat = {
        .dataOrig = &OD_RAM.x6747_terumoArterialCalculatedSO2pHStat,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6748_terumoArterialCalculatedSO2AStat = {
        .dataOrig = &OD_RAM.x6748_terumoArterialCalculatedSO2AStat,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6749_terumoArterialHCO3 = {
        .dataOrig = &OD_RAM.x6749_terumoArterialHCO3,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_674A_terumoArterialPotassium = {
        .dataOrig = &OD_RAM.x674A_terumoArterialPotassium,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_674B_terumoArterialTemperature = {
        .dataOrig = &OD_RAM.x674B_terumoArterialTemperature,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_674C_portalVeinPressure = {
        .dataOrig = &OD_RAM.x674C_portalVeinPressure,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_SDOClientParameter, NULL},
    {0x1800, 0x07, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x07, ODT_REC, &ODObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1802, 0x07, ODT_REC, &ODObjs.o_1802_TPDOCommunicationParameter, NULL},
    {0x1803, 0x07, ODT_REC, &ODObjs.o_1803_TPDOCommunicationParameter, NULL},
    {0x1804, 0x07, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter, NULL},
    {0x1805, 0x07, ODT_REC, &ODObjs.o_1805_TPDOCommunicationParameter, NULL},
    {0x1806, 0x07, ODT_REC, &ODObjs.o_1806_TPDOCommunicationParameter, NULL},
    {0x1807, 0x07, ODT_REC, &ODObjs.o_1807_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x05, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x06, ODT_REC, &ODObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x1A02, 0x06, ODT_REC, &ODObjs.o_1A02_TPDOMappingParameter, NULL},
    {0x1A03, 0x05, ODT_REC, &ODObjs.o_1A03_TPDOMappingParameter, NULL},
    {0x1A04, 0x03, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter, NULL},
    {0x1A05, 0x05, ODT_REC, &ODObjs.o_1A05_TPDOMappingParameter, NULL},
    {0x1A06, 0x05, ODT_REC, &ODObjs.o_1A06_TPDOMappingParameter, NULL},
    {0x1A07, 0x04, ODT_REC, &ODObjs.o_1A07_TPDOMappingParameter, NULL},
    {0x6401, 0x01, ODT_VAR, &ODObjs.o_6401_aterialPressure, NULL},
    {0x6402, 0x01, ODT_VAR, &ODObjs.o_6402_arterialFlowRate, NULL},
    {0x6403, 0x01, ODT_VAR, &ODObjs.o_6403_arterialSensorFlags, NULL},
    {0x6404, 0x01, ODT_VAR, &ODObjs.o_6404_portalVeinFlowRate, NULL},
    {0x6405, 0x01, ODT_VAR, &ODObjs.o_6405_portalVeinSensorFlags, NULL},
    {0x6406, 0x01, ODT_VAR, &ODObjs.o_6406_IVC_Pressure, NULL},
    {0x6407, 0x01, ODT_VAR, &ODObjs.o_6407_IVC_FlowRate, NULL},
    {0x6408, 0x01, ODT_VAR, &ODObjs.o_6408_IVC_SensorFlags, NULL},
    {0x6409, 0x01, ODT_VAR, &ODObjs.o_6409_bileFlowRate, NULL},
    {0x640A, 0x01, ODT_VAR, &ODObjs.o_640A_bileTemperature, NULL},
    {0x640B, 0x01, ODT_VAR, &ODObjs.o_640B_ambientTemperature_1, NULL},
    {0x640C, 0x01, ODT_VAR, &ODObjs.o_640C_ambientTemperature_2, NULL},
    {0x640D, 0x01, ODT_VAR, &ODObjs.o_640D_ambientTemperature_3, NULL},
    {0x640E, 0x01, ODT_VAR, &ODObjs.o_640E_levelSwitchState, NULL},
    {0x6701, 0x01, ODT_VAR, &ODObjs.o_6701_startCalibration, NULL},
    {0x6702, 0x01, ODT_VAR, &ODObjs.o_6702_personality, NULL},
    {0x6703, 0x01, ODT_VAR, &ODObjs.o_6703_K_code, NULL},
    {0x6704, 0x01, ODT_VAR, &ODObjs.o_6704_startMeasurements, NULL},
    {0x6711, 0x01, ODT_VAR, &ODObjs.o_6711_terumoPresent, NULL},
    {0x6712, 0x01, ODT_VAR, &ODObjs.o_6712_serialNumber, NULL},
    {0x6713, 0x01, ODT_VAR, &ODObjs.o_6713_K_CodeDisplay, NULL},
    {0x6714, 0x01, ODT_VAR, &ODObjs.o_6714_calibrationTimestamp, NULL},
    {0x6715, 0x01, ODT_VAR, &ODObjs.o_6715_CDI_SoftwareVersion, NULL},
    {0x6716, 0x01, ODT_VAR, &ODObjs.o_6716_shuntUsed, NULL},
    {0x6721, 0x01, ODT_VAR, &ODObjs.o_6721_calibratorPresent, NULL},
    {0x6722, 0x01, ODT_VAR, &ODObjs.o_6722_calibratorSerialNumber, NULL},
    {0x6723, 0x01, ODT_VAR, &ODObjs.o_6723_calibratorStateFlags, NULL},
    {0x6731, 0x01, ODT_VAR, &ODObjs.o_6731_terumoCalibratorStatus, NULL},
    {0x6732, 0x01, ODT_VAR, &ODObjs.o_6732_terumoCalibratorStatusFlags, NULL},
    {0x6733, 0x01, ODT_VAR, &ODObjs.o_6733_terumoCalibratorGas_1, NULL},
    {0x6734, 0x01, ODT_VAR, &ODObjs.o_6734_terumoCalibratorGas_2, NULL},
    {0x6735, 0x01, ODT_VAR, &ODObjs.o_6735_terumoCalibratorPresenceFlags, NULL},
    {0x6741, 0x01, ODT_VAR, &ODObjs.o_6741_terumoArterialpHpHStat, NULL},
    {0x6742, 0x01, ODT_VAR, &ODObjs.o_6742_terumoArterialpHAStat, NULL},
    {0x6743, 0x01, ODT_VAR, &ODObjs.o_6743_terumoArterialCO2pHStat, NULL},
    {0x6744, 0x01, ODT_VAR, &ODObjs.o_6744_terumoArterialCO2AStat, NULL},
    {0x6745, 0x01, ODT_VAR, &ODObjs.o_6745_terumoArterialO2pHStat, NULL},
    {0x6746, 0x01, ODT_VAR, &ODObjs.o_6746_terumoArterialO2AStat, NULL},
    {0x6747, 0x01, ODT_VAR, &ODObjs.o_6747_terumoArterialCalculatedSO2pHStat, NULL},
    {0x6748, 0x01, ODT_VAR, &ODObjs.o_6748_terumoArterialCalculatedSO2AStat, NULL},
    {0x6749, 0x01, ODT_VAR, &ODObjs.o_6749_terumoArterialHCO3, NULL},
    {0x674A, 0x01, ODT_VAR, &ODObjs.o_674A_terumoArterialPotassium, NULL},
    {0x674B, 0x01, ODT_VAR, &ODObjs.o_674B_terumoArterialTemperature, NULL},
    {0x674C, 0x01, ODT_VAR, &ODObjs.o_674C_portalVeinPressure, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
