/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.0.2-a-1-g742c4f3-dirty

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: Critical_Sensor_Hub_Benchmark.xdd
        File Version: 1

        Created:      10/23/2025 9:22:16 AM
        Created By:   David Cox
        Modified:     4/8/2026 1:13:02 PM
        Modified By:  

    Device Info:
        Vendor Name:  OrganOx
        Vendor ID:    0
        Product Name: OrganOx Critical Sensor Hub
        Product ID:   0

        Description:  metra-L Critical Sensor Hub
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_TPDO 8


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 8


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    char x1008_manufacturerDeviceName[8];
    char x1009_manufacturerHardwareVersion[6];
    char x100A_manufacturerSoftwareVersion[6];
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1804_TPDOCommunicationParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1805_TPDOCommunicationParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1806_TPDOCommunicationParameter;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1807_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
        uint32_t mappedObject_3;
        uint32_t mappedObject_4;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
        uint32_t mappedObject_3;
        uint32_t mappedObject_4;
        uint32_t mappedObject_5;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
        uint32_t mappedObject_3;
        uint32_t mappedObject_4;
        uint32_t mappedObject_5;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
        uint32_t mappedObject_3;
        uint32_t mappedObject_4;
    } x1A03_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
    } x1A04_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
        uint32_t mappedObject_3;
        uint32_t mappedObject_4;
    } x1A05_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
        uint32_t mappedObject_3;
        uint32_t mappedObject_4;
    } x1A06_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t mappedObject_1;
        uint32_t mappedObject_2;
        uint32_t mappedObject_3;
    } x1A07_TPDOMappingParameter;
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    uint16_t x6401_aterialPressure;
    uint16_t x6402_arterialFlowRate;
    uint16_t x6403_arterialSensorFlags;
    uint16_t x6404_portalVeinFlowRate;
    uint16_t x6405_portalVeinSensorFlags;
    uint16_t x6406_IVC_Pressure;
    uint16_t x6407_IVC_FlowRate;
    uint16_t x6408_IVC_SensorFlags;
    uint16_t x6409_bileFlowRate;
    uint8_t x640A_bileTemperature;
    uint8_t x640B_ambientTemperature_1;
    uint8_t x640C_ambientTemperature_2;
    uint8_t x640D_ambientTemperature_3;
    uint8_t x640E_levelSwitchState;
    uint8_t x6701_startCalibration;
    uint16_t x6702_personality;
    char x6703_K_code[6];
    uint8_t x6704_startMeasurements;
    uint8_t x6711_terumoPresent;
    char x6712_serialNumber[17];
    char x6713_K_CodeDisplay[6];
    uint32_t x6714_calibrationTimestamp;
    char x6715_CDI_SoftwareVersion[17];
    uint8_t x6716_shuntUsed;
    uint8_t x6721_calibratorPresent;
    char x6722_calibratorSerialNumber[17];
    uint16_t x6723_calibratorStateFlags;
    uint16_t x6731_terumoCalibratorStatus;
    uint16_t x6732_terumoCalibratorStatusFlags;
    uint16_t x6733_terumoCalibratorGas_1;
    uint16_t x6734_terumoCalibratorGas_2;
    uint8_t x6735_terumoCalibratorPresenceFlags;
    int16_t x6741_terumoArterialpHpHStat;
    int16_t x6742_terumoArterialpHAStat;
    int16_t x6743_terumoArterialCO2pHStat;
    int16_t x6744_terumoArterialCO2AStat;
    int16_t x6745_terumoArterialO2pHStat;
    int16_t x6746_terumoArterialO2AStat;
    int16_t x6747_terumoArterialCalculatedSO2pHStat;
    int16_t x6748_terumoArterialCalculatedSO2AStat;
    int16_t x6749_terumoArterialHCO3;
    int16_t x674A_terumoArterialPotassium;
    int16_t x674B_terumoArterialTemperature;
    uint16_t x674C_portalVeinPressure;
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H1007 &OD->list[5]
#define OD_ENTRY_H1008 &OD->list[6]
#define OD_ENTRY_H1009 &OD->list[7]
#define OD_ENTRY_H100A &OD->list[8]
#define OD_ENTRY_H1010 &OD->list[9]
#define OD_ENTRY_H1011 &OD->list[10]
#define OD_ENTRY_H1012 &OD->list[11]
#define OD_ENTRY_H1014 &OD->list[12]
#define OD_ENTRY_H1015 &OD->list[13]
#define OD_ENTRY_H1016 &OD->list[14]
#define OD_ENTRY_H1017 &OD->list[15]
#define OD_ENTRY_H1018 &OD->list[16]
#define OD_ENTRY_H1019 &OD->list[17]
#define OD_ENTRY_H1200 &OD->list[18]
#define OD_ENTRY_H1280 &OD->list[19]
#define OD_ENTRY_H1800 &OD->list[20]
#define OD_ENTRY_H1801 &OD->list[21]
#define OD_ENTRY_H1802 &OD->list[22]
#define OD_ENTRY_H1803 &OD->list[23]
#define OD_ENTRY_H1804 &OD->list[24]
#define OD_ENTRY_H1805 &OD->list[25]
#define OD_ENTRY_H1806 &OD->list[26]
#define OD_ENTRY_H1807 &OD->list[27]
#define OD_ENTRY_H1A00 &OD->list[28]
#define OD_ENTRY_H1A01 &OD->list[29]
#define OD_ENTRY_H1A02 &OD->list[30]
#define OD_ENTRY_H1A03 &OD->list[31]
#define OD_ENTRY_H1A04 &OD->list[32]
#define OD_ENTRY_H1A05 &OD->list[33]
#define OD_ENTRY_H1A06 &OD->list[34]
#define OD_ENTRY_H1A07 &OD->list[35]
#define OD_ENTRY_H6401 &OD->list[36]
#define OD_ENTRY_H6402 &OD->list[37]
#define OD_ENTRY_H6403 &OD->list[38]
#define OD_ENTRY_H6404 &OD->list[39]
#define OD_ENTRY_H6405 &OD->list[40]
#define OD_ENTRY_H6406 &OD->list[41]
#define OD_ENTRY_H6407 &OD->list[42]
#define OD_ENTRY_H6408 &OD->list[43]
#define OD_ENTRY_H6409 &OD->list[44]
#define OD_ENTRY_H640A &OD->list[45]
#define OD_ENTRY_H640B &OD->list[46]
#define OD_ENTRY_H640C &OD->list[47]
#define OD_ENTRY_H640D &OD->list[48]
#define OD_ENTRY_H640E &OD->list[49]
#define OD_ENTRY_H6701 &OD->list[50]
#define OD_ENTRY_H6702 &OD->list[51]
#define OD_ENTRY_H6703 &OD->list[52]
#define OD_ENTRY_H6704 &OD->list[53]
#define OD_ENTRY_H6711 &OD->list[54]
#define OD_ENTRY_H6712 &OD->list[55]
#define OD_ENTRY_H6713 &OD->list[56]
#define OD_ENTRY_H6714 &OD->list[57]
#define OD_ENTRY_H6715 &OD->list[58]
#define OD_ENTRY_H6716 &OD->list[59]
#define OD_ENTRY_H6721 &OD->list[60]
#define OD_ENTRY_H6722 &OD->list[61]
#define OD_ENTRY_H6723 &OD->list[62]
#define OD_ENTRY_H6731 &OD->list[63]
#define OD_ENTRY_H6732 &OD->list[64]
#define OD_ENTRY_H6733 &OD->list[65]
#define OD_ENTRY_H6734 &OD->list[66]
#define OD_ENTRY_H6735 &OD->list[67]
#define OD_ENTRY_H6741 &OD->list[68]
#define OD_ENTRY_H6742 &OD->list[69]
#define OD_ENTRY_H6743 &OD->list[70]
#define OD_ENTRY_H6744 &OD->list[71]
#define OD_ENTRY_H6745 &OD->list[72]
#define OD_ENTRY_H6746 &OD->list[73]
#define OD_ENTRY_H6747 &OD->list[74]
#define OD_ENTRY_H6748 &OD->list[75]
#define OD_ENTRY_H6749 &OD->list[76]
#define OD_ENTRY_H674A &OD->list[77]
#define OD_ENTRY_H674B &OD->list[78]
#define OD_ENTRY_H674C &OD->list[79]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[3]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[4]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[5]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[6]
#define OD_ENTRY_H1009_manufacturerHardwareVersion &OD->list[7]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[8]
#define OD_ENTRY_H1010_storeParameters &OD->list[9]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[10]
#define OD_ENTRY_H1012_COB_IDTimeStampObject &OD->list[11]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[12]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[13]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[14]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[15]
#define OD_ENTRY_H1018_identity &OD->list[16]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[17]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[18]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[19]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[20]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[21]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[22]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[23]
#define OD_ENTRY_H1804_TPDOCommunicationParameter &OD->list[24]
#define OD_ENTRY_H1805_TPDOCommunicationParameter &OD->list[25]
#define OD_ENTRY_H1806_TPDOCommunicationParameter &OD->list[26]
#define OD_ENTRY_H1807_TPDOCommunicationParameter &OD->list[27]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[28]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[29]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[30]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[31]
#define OD_ENTRY_H1A04_TPDOMappingParameter &OD->list[32]
#define OD_ENTRY_H1A05_TPDOMappingParameter &OD->list[33]
#define OD_ENTRY_H1A06_TPDOMappingParameter &OD->list[34]
#define OD_ENTRY_H1A07_TPDOMappingParameter &OD->list[35]
#define OD_ENTRY_H6401_aterialPressure &OD->list[36]
#define OD_ENTRY_H6402_arterialFlowRate &OD->list[37]
#define OD_ENTRY_H6403_arterialSensorFlags &OD->list[38]
#define OD_ENTRY_H6404_portalVeinFlowRate &OD->list[39]
#define OD_ENTRY_H6405_portalVeinSensorFlags &OD->list[40]
#define OD_ENTRY_H6406_IVC_Pressure &OD->list[41]
#define OD_ENTRY_H6407_IVC_FlowRate &OD->list[42]
#define OD_ENTRY_H6408_IVC_SensorFlags &OD->list[43]
#define OD_ENTRY_H6409_bileFlowRate &OD->list[44]
#define OD_ENTRY_H640A_bileTemperature &OD->list[45]
#define OD_ENTRY_H640B_ambientTemperature_1 &OD->list[46]
#define OD_ENTRY_H640C_ambientTemperature_2 &OD->list[47]
#define OD_ENTRY_H640D_ambientTemperature_3 &OD->list[48]
#define OD_ENTRY_H640E_levelSwitchState &OD->list[49]
#define OD_ENTRY_H6701_startCalibration &OD->list[50]
#define OD_ENTRY_H6702_personality &OD->list[51]
#define OD_ENTRY_H6703_K_code &OD->list[52]
#define OD_ENTRY_H6704_startMeasurements &OD->list[53]
#define OD_ENTRY_H6711_terumoPresent &OD->list[54]
#define OD_ENTRY_H6712_serialNumber &OD->list[55]
#define OD_ENTRY_H6713_K_CodeDisplay &OD->list[56]
#define OD_ENTRY_H6714_calibrationTimestamp &OD->list[57]
#define OD_ENTRY_H6715_CDI_SoftwareVersion &OD->list[58]
#define OD_ENTRY_H6716_shuntUsed &OD->list[59]
#define OD_ENTRY_H6721_calibratorPresent &OD->list[60]
#define OD_ENTRY_H6722_calibratorSerialNumber &OD->list[61]
#define OD_ENTRY_H6723_calibratorStateFlags &OD->list[62]
#define OD_ENTRY_H6731_terumoCalibratorStatus &OD->list[63]
#define OD_ENTRY_H6732_terumoCalibratorStatusFlags &OD->list[64]
#define OD_ENTRY_H6733_terumoCalibratorGas_1 &OD->list[65]
#define OD_ENTRY_H6734_terumoCalibratorGas_2 &OD->list[66]
#define OD_ENTRY_H6735_terumoCalibratorPresenceFlags &OD->list[67]
#define OD_ENTRY_H6741_terumoArterialpHpHStat &OD->list[68]
#define OD_ENTRY_H6742_terumoArterialpHAStat &OD->list[69]
#define OD_ENTRY_H6743_terumoArterialCO2pHStat &OD->list[70]
#define OD_ENTRY_H6744_terumoArterialCO2AStat &OD->list[71]
#define OD_ENTRY_H6745_terumoArterialO2pHStat &OD->list[72]
#define OD_ENTRY_H6746_terumoArterialO2AStat &OD->list[73]
#define OD_ENTRY_H6747_terumoArterialCalculatedSO2pHStat &OD->list[74]
#define OD_ENTRY_H6748_terumoArterialCalculatedSO2AStat &OD->list[75]
#define OD_ENTRY_H6749_terumoArterialHCO3 &OD->list[76]
#define OD_ENTRY_H674A_terumoArterialPotassium &OD->list[77]
#define OD_ENTRY_H674B_terumoArterialTemperature &OD->list[78]
#define OD_ENTRY_H674C_portalVeinPressure &OD->list[79]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = 0;\
    (config).ENTRY_H1400 = NULL;\
    (config).ENTRY_H1600 = NULL;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_GFC = OD_CNT_STORAGE;\
    (config).CNT_GFC = OD_EM_PROD;\
    (config).CNT_GFC = OD_SYNC_PROD;\
    (config).CNT_GFC = OD_HB_PROD;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
